# Generated by Django 4.0.10 on 2023-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://img.freepik.com/free-icon/placeholder_318-855980.jpg', max_length=500),
        ),
    ]
